import Navbar from "@component/component/navbar";
import "../globals.css";

export const metadata = {
  title: "Tasty Tales Authentication",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-red-50 to-amber-50">
        {children}
      </body>
    </html>
  );
}
