import Navbar from "@component/component/navbar";
import "../globals.css";

export const metadata = {
  title: "Tasty Tales",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
