import NextAuthSessionProvider from "@component/component/SessionProvider";
import "./globals.css";

export const metadata = {
  title: "Tasty Tales",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-red-50 to-amber-50">
        <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
      </body>
    </html>
  );
}
