import Navbar from "@component/component/navbar";

export const metadata = {
  title: "Tasty Tales",
  description: "Generated by Next.js",
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="max-w-7xl mx-auto">
      <Navbar />
      {children}
    </div>
  );
}
